In [2]:
#Normalization Problem 

#Import Numpy Library
import numpy as np

#Start Program
#Create 5x5 ndarray with random values
X = np.random.rand(5, 5)

#Calculate the element-wise mean and standard deviation
mean_X = X.mean()
std_X = X.std()

#Check for standard deviation to avoid division by zero
if std_X == 0:
    print("Standard deviation is zero, normalization cannot be performed.")
else:
    #Normalize Array 
    X_normalized = (X - mean_X) / std_X

    #Save the normalized array to a .npy file
    np.save('X_normalized.npy', X_normalized)

    #Output: Original and Normalized Array
    print("Original Array:\n", X)
    print("\nNormalized Array:\n", X_normalized)

    #Load and verify the saved normalized array
    loaded_X_normalized = np.load('X_normalized.npy')
    print("\nLoaded Normalized Array from File:\n", loaded_X_normalized)


Original Array:
 [[0.17566305 0.8282231  0.86569971 0.43591808 0.14939429]
 [0.17773708 0.60094529 0.17280191 0.99337313 0.90352959]
 [0.90370288 0.51204365 0.7161868  0.82571235 0.73991685]
 [0.09378146 0.61808606 0.57508604 0.20795909 0.54832408]
 [0.01320675 0.52606646 0.97550332 0.68995181 0.41262693]]

Normalized Array:
 [[-1.24986834  0.94977069  1.07609624 -0.37260481 -1.33841467]
 [-1.24287724  0.18366626 -1.2595126   1.50645578  1.20361261]
 [ 1.20419674 -0.11600195  0.57212053  0.9413075   0.65210938]
 [-1.5258735   0.24144412  0.09650034 -1.14100536  0.00629153]
 [-1.79747344 -0.06873408  1.4462205   0.48368804 -0.45111427]]

Loaded Normalized Array from File:
 [[-1.24986834  0.94977069  1.07609624 -0.37260481 -1.33841467]
 [-1.24287724  0.18366626 -1.2595126   1.50645578  1.20361261]
 [ 1.20419674 -0.11600195  0.57212053  0.9413075   0.65210938]
 [-1.5258735   0.24144412  0.09650034 -1.14100536  0.00629153]
 [-1.79747344 -0.06873408  1.4462205   0.48368804 -0.45111427]]


In [8]:
#Divisible by 3 Problem 

#Import Numpy Library
import numpy as np  

#Start Program
#Create 10x10 ndarray of squares of integers from 1 to 100
A = np.arange(1, 101)**2
A = A.reshape((10, 10))  # Reshape into a 10x10 array

#Output: 10x10 array
print("10x10 Array of Squares of the First 100 Positive Integers:\n", A)

#Determine elements divisible by 3 using modulo operation
div_by_3 = A[A % 3 == 0]

#Output: Elements divisible by 3
print("\nElements Divisible by 3:\n", div_by_3)

#Check if there are no elements divisible by 3 (edge case)
if div_by_3.size == 0:
    print("\nNo elements divisible by 3 were found in the array.")
else:
    #Save results to a .npy file
    np.save('div_by_3.npy', div_by_3)

    


10x10 Array of Squares of the First 100 Positive Integers:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
